export enum OfficerRole {
  CEO = 'CEO',
  TREASURER = 'TREASURER',
  CFO = 'CFO',
  SECRETARY = 'SECRETARY',
  PRESIDENT = 'PRESIDENT',
  ASSISTANT_SECRETARY = 'ASSISTANT_SECRETARY',
  VP = 'VP',
  OTHER = 'OTHER',
  CHAIR = 'CHAIR'
}
