packages:
  - web/corps
  - web/person-roles
  - packages/**

catalog:
  '@axe-core/playwright': 4.11.0
  '@iconify-json/mdi': 1.2.3
  '@nuxt/test-utils': 3.21.0
  dotenv: 17.2.3
  typescript: 5.9.3
  vue-tsc: 3.2.2
  nuxt: 4.2.2
  vue: 3.5.26
  vue-router: 4.6.4

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
- '@sbc-connect/*'
autoInstallPeers: true
shamefullyHoist: true
