packages:
  - web/corps
  - web/person-roles
  - web/registry-home
  - packages/**

catalog:
  '@axe-core/playwright': 4.11.3
  '@iconify-json/mdi': 1.2.3
  '@nuxt/test-utils': 3.21.0
  dotenv: 17.4.2
  typescript: 6.0.3
  vue-tsc: 3.3.1
  nuxt: 4.4.6
  vue: 3.5.34
  vue-router: 5.0.7
  '@types/node': 25.5.0
  '@faker-js/faker': 10.4.0

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@sbc-connect/*'
autoInstallPeers: true
shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  '@sbc-connect/nuxt-auth': true
  '@sbc-connect/nuxt-base': true
  '@sbc-connect/nuxt-business-base': true
  '@sbc-connect/nuxt-forms': true
  '@sbc-connect/nuxt-pay': true
  '@tailwindcss/oxide': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
