/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedAction {
  ADDRESS_CHANGE_FILING = 'ADDRESS_CHANGE_FILING',
  ADMIN_DISSOLUTION_FILING = 'ADMIN_DISSOLUTION_FILING',
  AGM_EXTENSION_FILING = 'AGM_EXTENSION_FILING',
  AGM_CHG_LOCATION_FILING = 'AGM_CHG_LOCATION_FILING',
  ALTERATION_FILING = 'ALTERATION_FILING',
  AMALGAMATION_FILING = 'AMALGAMATION_FILING',
  ANNUAL_REPORT_FILING = 'ANNUAL_REPORT_FILING',
  CONSENT_AMALGAMATION_OUT_FILING = 'CONSENT_AMALGAMATION_OUT_FILING',
  CONSENT_CONTINUATION_OUT_FILING = 'CONSENT_CONTINUATION_OUT_FILING',
  CORRECTION_FILING = 'CORRECTION_FILING',
  COURT_ORDER_FILING = 'COURT_ORDER_FILING',
  DETAIL_COMMENTS = 'DETAIL_COMMENTS',
  DIGITAL_CREDENTIALS = 'DIGITAL_CREDENTIALS',
  DIRECTOR_CHANGE_FILING = 'DIRECTOR_CHANGE_FILING',
  DOCUMENT_RECORDS = 'DOCUMENT_RECORDS',
  EDITABLE_CERTIFY_NAME = 'EDITABLE_CERTIFY_NAME',
  FIRM_CHANGE_FILING = 'FIRM_CHANGE_FILING',
  FIRM_CONVERSION_FILING = 'FIRM_CONVERSION_FILING',
  OFFICER_CHANGE_FILING = 'OFFICER_CHANGE_FILING',
  NO_CONTACT_INFO = 'NO_CONTACT_INFO',
  NOTICE_WITHDRAWAL_FILING = 'NOTICE_WITHDRAWAL_FILING',
  OVERRIDE_NIGS = 'OVERRIDE_NIGS',
  REGISTRATION_FILING = 'REGISTRATION_FILING',
  RESTORATION_REINSTATEMENT_FILING = 'RESTORATION_REINSTATEMENT_FILING',
  SPECIAL_RESOLUTION_FILING = 'SPECIAL_RESOLUTION_FILING',
  STAFF_BREADCRUMBS = 'STAFF_BREADCRUMBS',
  STAFF_COMMENTS = 'STAFF_COMMENTS',
  STAFF_FILINGS = 'STAFF_FILINGS',
  TRANSITION_FILING = 'TRANSITION_FILING',
  VOLUNTARY_DISSOLUTION_FILING = 'VOLUNTARY_DISSOLUTION_FILING'
}
