/**
 * Corp type codes, used as keys to get corp info.
 * (sorted by code)
 */
export enum CorpTypeCd {
  EXTRA_PRO_A = 'A',
  EXTRA_PRO_B = 'B',
  BC_COMPANY = 'BC',
  BENEFIT_COMPANY = 'BEN',
  CONTINUE_IN = 'C',
  BEN_CONTINUE_IN = 'CBEN',
  BC_CCC = 'CC',
  CCC_CONTINUE_IN = 'CCC',
  CEMETARY = 'CEM',
  COOP = 'CP',
  CORPORATION = 'CR', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  CONT_IN_SOCIETY = 'CS',
  ULC_CONTINUE_IN = 'CUL',
  DOING_BUSINESS_AS = 'DBA', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  EXTRA_PRO_REG = 'EPR',
  FINANCIAL = 'FI',
  FOREIGN = 'FOR',
  SOLE_PROPRIETORSHIP = 'FR', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  PARTNERSHIP = 'GP',
  LIBRARY = 'LIB',
  LICENSED = 'LIC',
  LL_PARTNERSHIP = 'LL',
  LIMITED_CO = 'LLC',
  LIM_PARTNERSHIP = 'LP',
  MISC_FIRM = 'MF',
  PRIVATE_ACT = 'PA',
  PARISHES = 'PAR',
  PENSION_FUND_SOCIETY = 'PFS',
  CO_1860 = 'QA',
  CO_1862 = 'QB',
  CO_1878 = 'QC',
  CO_1890 = 'QD',
  CO_1897 = 'QE',
  REGISTRATION = 'REG',
  XPRO_LIMITED_LIABILITY_COMPANY = 'RLC', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  RAILWAYS = 'RLY',
  SOCIETY = 'S',
  SOCIETY_BRANCH = 'SB',
  SOCIETY_NR = 'SO', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  SOLE_PROP = 'SP',
  TRUST = 'T',
  TRAMWAYS = 'TMY',
  UNLIMITED_LIABILITY_COMPANY = 'UL', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  BC_ULC_COMPANY = 'ULC',
  ULC_CO_1860 = 'UQA',
  ULC_CO_1862 = 'UQB',
  ULC_CO_1878 = 'UQC',
  ULC_CO_1890 = 'UQD',
  ULC_CO_1897 = 'UQE',
  XPRO_COOP = 'XCP',
  XPRO_CORPORATION = 'XCR',
  XPRO_LL_PARTNR = 'XL',
  XPRO_LIMITED_LIABILITY_PARTNERSHIP = 'XLL', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  XPRO_LIM_PARTNR = 'XP',
  XPRO_LIMITED_PARTNERSHIP = 'XLP', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  XPRO_SOCIETY = 'XS',
  XPRO_SOCIETY_NR = 'XSO', // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
  XPRO_UNLIMITED_LIABILITY_COMPANY = 'XUL' // SPECIAL NAMEREQUEST-ONLY ENTITY TYPE
}
