/* eslint-disable @typescript-eslint/prefer-literal-enum-member */
/** Filing sub-types used by Legal API. */
export enum FilingSubType {
  ADMIN_FREEZE = 'adminFreeze',
  ADMIN_UNFREEZE = 'adminUnfreeze',
  AMALGAMATION_REGULAR = AmalgamationType.REGULAR,
  AMALGAMATION_HORIZONTAL = AmalgamationType.HORIZONTAL,
  AMALGAMATION_VERTICAL = AmalgamationType.VERTICAL,
  AMEND_RECEIVER = ReceiverType.AMEND,
  APPOINT_RECEIVER = ReceiverType.APPOINT,
  CEASE_RECEIVER = ReceiverType.CEASE,
  CHANGE_ADDRESS_RECEIVER = ReceiverType.ADDRESS,
  COURT_ORDERED_LIQUIDATION = 'courtOrderedLiquidation',
  DISSOLUTION_ADMINISTRATIVE = 'administrative',
  DISSOLUTION_INVOLUNTARY = 'involuntary',
  DISSOLUTION_VOLUNTARY = 'voluntary',
  FULL_RESTORATION = RestorationType.FULL,
  INTENT_TO_LIQUIDATE = 'intentToLiquidate',
  LIMITED_RESTORATION = RestorationType.LIMITED,
  LIMITED_RESTORATION_EXTENSION = RestorationType.LTD_EXTEND,
  LIMITED_RESTORATION_TO_FULL = RestorationType.LTD_TO_FULL,
  LIQUIDATION_REPORT = 'liquidationReport',
  MANAGE_RECEIVERS = 'manageReceivers',
  MANAGE_LIQUIDATORS = 'manageLiquidators',
  VOLUNTARY_LIQUIDATION = 'voluntaryLiquidation'

  // FUTURE: add these dissolution names as needed
  // DISS_D1A = 'DISS_1_ADMIN',
  // DISS_D1F = 'DISS_1_FILE',
  // DISS_D1T = 'DISS_1_TRANS',
  // DISS_D2A = 'DISS_2_ADMIN',
  // DISS_D2F = 'DISS_2_FILE',
  // DISS_D2T = 'DISS_2_TRANS',
  // DISS_HDA = 'DISS_ADMIN',
  // DISS_HDB = 'DISS_CONVERTED',
  // DISS_HDF = 'DISS_FAIL_FILE',
  // DISS_HDT = 'DISS_FAIL_TRANS',
  // DISS_HDP = 'DISS_LLP_REG',
  // DISS_HDO = 'DISS_OTHER',
  // DISS_HDV = 'DISS_VOLUNTARY',
}
