export enum LDFlag {
  BannerText = 'banner-text',
  BusinessesToManageInColin = 'businesses-to-manage-in-colin',
  EnabledBusinessSummaryEntities = 'enabled-business-summary-entities',
  EnableDigitalCredentials = 'enable-digital-credentials',
  EnableDocumentRecords = 'enable-document-records',
  EnableWithdrawalAction = 'enable-withdrawal-action',
  SpecialResolutionUIEnabled = 'special-resolution-ui-enabled',
  SupportedAgmExtensionEntities = 'supported-agm-extension-entities',
  SupportedAgmLocationChgEntities = 'supported-agm-location-chg-entities',
  SupportedAmalgamationEntities = 'supported-amalgamation-entities',
  SupportedAmalgamationOutEntities = 'supported-amalgamation-out-entities',
  SupportedArCorrectionEntities = 'supported-ar-correction-entities',
  SupportedBusinessSummaryEntities = 'supported-business-summary-entities',
  SupportedConsentAmalgamationOutEntities = 'supported-consent-amalgamation-out-entities',
  SupportedConsentContinuationOutEntities = 'supported-consent-continuation-out-entities',
  SupportedContinuationOutEntities = 'supported-continuation-out-entities',
  SupportedCorrectionEntities = 'supported-correction-entities',
  SupportedDissolutionEntities = 'supported-dissolution-entities',
  SupportedRestorationEntities = 'supported-restoration-entities',
  SupportedPutBackOnEntities = 'supported-put-back-on-entities',
  UseBusinessApiGwURL = 'use-business-api-gw-url'
}
