export enum ManageAllowedAction {
  ADD = 'ADD',
  ADDRESS_CHANGE = 'ADDRESS_CHANGE',
  EFFECTIVE_DATE_CHANGE = 'EFFECTIVE_DATE_CHANGE',
  NAME_CHANGE = 'NAME_CHANGE',
  REMOVE = 'REMOVE',
  ROLE_CHANGE = 'ROLE_CHANGE'
}
