/** List of authorized actions (permissions). See IsAuthorized(). */
export enum AuthorizedActions {
  ADD_ENTITY_NO_AUTHENTICATION = 'ADD_ENTITY_NO_AUTHENTICATION',
  MANAGE_BUSINESS = 'MANAGE_BUSINESS',
  MANAGE_NR = 'MANAGE_NR',
  MANAGE_OTHER_ORGANIZATION = 'MANAGE_OTHER_ORGANIZATION',
  MANAGE_SOCIETY = 'MANAGE_SOCIETY',
  RESTORATION_REINSTATEMENT_FILING = 'RESTORATION_REINSTATEMENT_FILING',
  RESUME_DRAFT = 'RESUME_DRAFT',
  SEARCH_BUSINESS_NR = 'SEARCH_BUSINESS_NR',
  STAFF_BREADCRUMBS = 'STAFF_BREADCRUMBS',
  STAFF_DASHBOARD = 'STAFF_DASHBOARD',
  AMALGAMATION_FILING = 'AMALGAMATION_FILING',
  CONTINUATION_IN_FILING = 'CONTINUATION_IN_FILING'
}
