export enum EntityAlertTypes {
  FROZEN = 'FROZEN',
  BADSTANDING = 'BAD_STANDING',
  LIQUIDATION = 'LIQUIDATION',
  DISSOLUTION = 'DISSOLUTION',
  PROCESSING = 'PROCESSING',
  EXPIRED = 'EXPIRED',
  FUTURE_EFFECTIVE = 'FUTURE_EFFECTIVE',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED'
}
