CREATE DATABASE "business-ar";
GRANT ALL PRIVILEGES ON DATABASE "business-ar" TO ${POSTGRES_APP_USERNAME};

CREATE DATABASE "business-ar-test";
GRANT ALL PRIVILEGES ON DATABASE "business-ar-test" TO ${POSTGRES_APP_USERNAME};