export enum FilingStatus {
    ACTIVE = 'ACTIVE',
    APPROVED = 'APPROVED',
    AWAITING_REVIEW = 'AWAITING_REVIEW',
    CHANGE_REQUESTED = 'CHANGE_REQUESTED',
    DRAFT = 'DRAFT',
    REJECTED = 'REJECTED',
    PENDING = 'PENDING',
    PAID = 'PAID',
    WITHDRAWN = 'WITHDRAWN'
  }
