export enum LDFlags {
  AlternateNamesMbr = 'enable-alternate-names-mbr',
  AffiliationInvitationRequestAccess = 'enable-affiliation-invitation-request-access',
  BannerText = 'banner-text',
  BusSearchLink = 'bus-search-staff-link',
  EnableBcCccUlc = 'enable-bc-ccc-ulc',
  EnableBusinessNrSearch = 'enable-business-nr-search',
  EnableDetailsFilter = 'enable-transactions-detail-filter',
  EnableEFTPaymentMethod = 'enable-eft-payment-method',
  IaSupportedEntities = 'ia-supported-entities',
  ProductBCAStatus = 'product-BCA-status',
  ProductBusSearchPremTooltip = 'product-BUSINESS_SEARCH-prem-tooltip',
  ProductBusSearchStatus = 'product-BUSINESS_SEARCH-status',
  ProductCSOStatus = 'product-CSO-status',
  ProductSiteRegistryStatus = 'product-ESRA-status',
  ProductWillsStatus = 'product-VS-status',
  SupportedAmalgamationEntities = 'supported-amalgamation-entities',
  SupportedContinuationInEntities = 'supported-continuation-in-entities',
  SentryEnable = 'sentry-enable',
  SupportRestorationEntities = 'supported-restoration-entities',
  AllowableBusinessSearchTypes = 'allowable-business-search-types',
  AllowableBusinessPasscodeTypes = 'allowable-business-passcode-types',
  EnableAffiliationDelegation = 'enable-affiliation-delegation',
  EnableCreditCardPremium = 'enable-credit-card-premium'
}
