export enum NrState {
  APPROVED = 'APPROVED',
  DRAFT = 'DRAFT',
  HOLD = 'HOLD',
  REJECTED = 'REJECTED',
  CONDITION = 'CONDITION',
  CONDITIONAL = 'CONDITIONAL',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  CONSUMED = 'CONSUMED',
  PROCESSING = 'PROCESSING',
  INPROGRESS = 'INPROGRESS'
}
