"""empty message

Revision ID: 0a47d4f8452d
Revises: fe1a62b01dfa
Create Date: 2024-06-27 17:06:00.044221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a47d4f8452d'
down_revision = 'fe1a62b01dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ar_reminder_year', sa.Integer(), nullable=True))
        batch_op.drop_column('last_ar_reminder_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ar_reminder_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('last_ar_reminder_year')

    # ### end Alembic commands ###
