"""empty message

Revision ID: 14bcb583d3cc
Revises: 5bb17da90971
Create Date: 2024-05-04 18:29:48.002107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bcb583d3cc'
down_revision = '5bb17da90971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.String(length=1000), nullable=False),
    sa.Column('message', sa.String(length=8000), nullable=False),
    sa.Column('sent_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('additional_message', sa.String(length=4000), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colin_event_ids',
    sa.Column('colin_event_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.PrimaryKeyConstraint('colin_event_id'),
    sa.UniqueConstraint('colin_event_id')
    )
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_account', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.drop_column('payment_account')

    op.drop_table('colin_event_ids')
    op.drop_table('invitations')
    # ### end Alembic commands ###
