"""empty message

Revision ID: 6abbcc70e44c
Revises: 
Create Date: 2024-04-17 07:16:36.413087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abbcc70e44c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('middlename', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('sub', sa.String(length=36), nullable=True),
    sa.Column('iss', sa.String(length=1024), nullable=True),
    sa.Column('idp_userid', sa.String(length=256), nullable=True),
    sa.Column('login_source', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_idp_userid'), ['idp_userid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_idp_userid'))

    op.drop_table('users')
    # ### end Alembic commands ###
