"""empty message

Revision ID: d979fbe60318
Revises: 14bcb583d3cc
Create Date: 2024-06-15 00:06:57.919605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd979fbe60318'
down_revision = '14bcb583d3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colin_event_ids', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['colin_event_id'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_recipients'), ['recipients'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_invitations_recipients'))

    with op.batch_alter_table('colin_event_ids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
