name: Business People UI CI

on:
  pull_request:
    paths:
      - "web/person-roles/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "./web/person-roles"

jobs:
  business-people-ui-ci:
    uses: pwei1018/bcregistry-sre/.github/workflows/frontend-ci.yaml@main 
    with:
      app_name: "business-people"
      working_directory: "./web/person-roles"
      codecov_flag: "personroles"
      node_version: 20
      pnpm_version: 10.0.0